[pytest]
markers =
    asyncio: mark test as async coroutine
filterwarnings =
    ignore:urllib3 v2 only supports OpenSSL:urllib3.exceptions.NotOpenSSLWarning
    ignore::urllib3.exceptions.NotOpenSSLWarning
