from setuptools import setup, find_packages

setup(
    name="rts_ai_fx_trading",
    version="3.0",
    description="RTS - AI FX Trading System with ML and risk management",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.9",
    install_requires=[
        "pandas>=2.3.0",
        "numpy>=1.26.4,<2.0.0",
        "scikit-learn>=1.6.0",
        "matplotlib>=3.9.0",
        "seaborn>=0.13.0",
        "ta-lib>=0.6.0",
        "yfinance>=1.2.0",
        "ccxt>=4.5.0",
        "tensorflow>=2.15.0,<2.16.0",
        "ctrader-open-api>=0.9.2",
        "twisted>=24.3.0",
        "service-identity>=24.2.0",
        "requests>=2.32.0",
        "hmmlearn>=0.3.0",
        "fastapi>=0.128.0",
        "uvicorn>=0.39.0",
        "loguru>=0.7.0",
        "websockets>=15.0.0",
        "pyyaml>=6.0.0",
    ],
)
